server:
  port: 8080
eureka:
  instance:
    appname: TEST-SERVICE
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
spring:
  application:
    name: APPLICATION-SERVICE