server:
  port: 8082
spring:
  application:
    name: APPLICATION-CLIENT
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${eureka.instance.appname}:${server.port}:@project.version@
    appname: TEST-CLIENT
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true