management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    flyway:
      enabled: true
    health:
      roles:
      show-details: when_authorized
info:
  version: @project.version@
