spring:
  cloud:
    gateway:
      routes:
      - id: baidu
        uri: https://www.baidu.com
        order: 10000
        predicates:
          - name: Path
            args:
              path1: /baidu/**
              path2: /tencent/**
        filters:
          - SetPath=/

logging:
  level:
    org.springframework.cloud.gateway: debug