server:
  port: 8081
spring:
  application:
    name: APPLICATION-CLIENT
eureka:
  instance:
    hostname: TEST-CLIENT
    instance-id: ${spring.cloud.client.ip-address}:${eureka.instance.hostname}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/